spring:
  application:
    name: zuul-gateway
server:
   port: 8099
   
eureka:
  client:
    #registerWithEureka: false    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    a:      
      path: /microservice-teacher/**
      sensitiveHeaders:
      url: http://localhost:8083
    b:
      path: /microservice-course/**
      sensitiveHeaders:
      url: http://localhost:8084
